import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

function read(relativePath: string) {
  return readFileSync(resolve(process.cwd(), relativePath), 'utf8')
}

describe('production contracts', () => {
  it('keeps the legacy Vercel redirect scoped to public profile routes', () => {
    const config = JSON.parse(read('vercel.json')) as {
      redirects?: Array<{ source: string; destination: string; permanent?: boolean; has?: Array<{ type: string; value: string }> }>
    }
    const redirects = config.redirects || []
    expect(redirects).toHaveLength(1)
    expect(redirects[0]).toMatchObject({
      source: '/p/:identifier',
      destination: 'https://connect.oxxengroup.com/p/:identifier',
      permanent: true,
    })
    expect(redirects[0].has).toContainEqual({ type: 'host', value: 'oxxen-connect.vercel.app' })
    expect(redirects.some(rule => rule.source.includes('/admin'))).toBe(false)
    expect(redirects.some(rule => rule.source.includes('/api'))).toBe(false)
  })

  it('protects permanent public IDs and reserves historical aliases in the database migration', () => {
    const sql = read('supabase/migrations/20260830_sprint1_production_hardening.sql')
    expect(sql).toContain('create unique index if not exists idx_oxxen_connect_cards_public_id')
    expect(sql).toContain('alter column public_id set not null')
    expect(sql).toContain("raise exception 'public_id is permanent and cannot be changed'")
    expect(sql).toContain('before update of public_id on public.oxxen_connect_cards')
    expect(sql).toContain('alias text not null unique')
    expect(sql).toContain('Preserve the old slug and reserve the new one for this same card.')
    expect(sql).toContain('This slug was previously assigned to another card and cannot be reused')
  })

  it('keeps public analytics constrained and rate limited', () => {
    const sql = read('supabase/migrations/20260830_sprint1_production_hardening.sql')
    for (const event of ['view','whatsapp','phone','email','website','instagram','facebook','tiktok','linkedin','maps','vcard','share']) {
      expect(sql).toContain(`'${event}'`)
    }
    expect(sql).toContain("octet_length(coalesce(p_metadata, '{}'::jsonb)::text) > 2048")
    expect(sql).toContain('length(p_session_id) > 100')
    expect(sql).toContain('if v_recent_count >= 30 then')
    expect(sql).toContain("now() - interval '10 minutes'")
    expect(sql).toContain('raw IP addresses are never persisted')
  })

  it('requires aal2 for OWNER access to operational data', () => {
    const sql = read('supabase/migrations/20260831_sprint2_closeout_mfa.sql')
    expect(sql).toContain("a.role in ('OWNER')")
    expect(sql).toContain("(select auth.jwt()->>'aal') = 'aal2'")
    for (const table of ['oxxen_connect_cards', 'oxxen_connect_card_aliases', 'oxxen_connect_analytics_events', 'oxxen_connect_audit_logs']) {
      expect(sql).toContain(`on public.${table}`)
    }
    expect(sql).toContain("bucket_id <> 'oxxen-connect-media'")
  })

  it('restores original card identities instead of generating replacements', () => {
    const restore = read('scripts/restore-backup.mjs')
    expect(restore).toContain("const publicIds = new Set(cards.map(card => card.public_id))")
    expect(restore).toContain("const aliasValues = new Set(aliases.map(alias => alias.alias))")
    expect(restore).toContain('Preserve original card id, public_id and aliases. Never generate replacements during restore.')
    expect(restore).toContain("await upsertBatches('oxxen_connect_cards', cards)")
    expect(restore).toContain("await upsertBatches('oxxen_connect_card_aliases', aliases)")
  })

  it('defines S3.3 as one additive NFC migration with nullable unique UID and permanent public_id separation', () => {
    const sql = read('supabase/migrations/20260901_sprint3_3_nfc_inventory.sql')
    expect(sql).toContain('create table if not exists public.oxxen_connect_nfc_assets')
    expect(sql).toContain('asset_number bigint generated by default as identity')
    expect(sql).toContain("new.asset_code := 'NFC-' || lpad(new.asset_number::text, 6, '0')")
    expect(sql).toContain('create unique index if not exists uq_oxxen_connect_nfc_assets_uid')
    expect(sql).toContain('on public.oxxen_connect_nfc_assets(uid) where uid is not null')
    expect(sql).not.toContain('new.status in (\'programmed\',\'assigned\',\'delivered\') and new.uid is null')
    expect(sql).toContain('public_id remains the permanent digital identity')
  })

  it('enforces the NFC lifecycle, role model and least-privilege grants in the migration', () => {
    const sql = read('supabase/migrations/20260901_sprint3_3_nfc_inventory.sql')
    for (const status of ['available','reserved','programmed','assigned','delivered','defective','lost','retired']) {
      expect(sql).toContain(`'${status}'`)
    }
    expect(sql).toContain("old.status = 'reserved' and new.status in ('available','programmed','defective','lost','retired')")
    expect(sql).toContain("old.status = 'assigned' and new.status in ('delivered','defective','lost','retired')")
    expect(sql).not.toContain("old.status = 'delivered' and new.status")
    expect(sql).toContain("a.role in ('OWNER','ADMIN','EDITOR','SUPPORT','SALES')")
    expect(sql).toContain("a.role in ('OWNER','ADMIN')")
    expect(sql).toContain("revoke all on table public.oxxen_connect_nfc_assets from public, anon, authenticated")
    expect(sql).not.toMatch(/grant\s+delete/i)
    expect(sql).not.toMatch(/grant\s+truncate/i)
  })

  it('keeps bulk creation bounded and reservation atomic under concurrency', () => {
    const sql = read('supabase/migrations/20260901_sprint3_3_nfc_inventory.sql')
    expect(sql).toContain('p_quantity < 1 or p_quantity > 500')
    expect(sql).toContain('for update skip locked')
    expect(sql).toContain('if v_selected <> p_quantity then')
    expect(sql).toContain("status = 'reserved'")
    expect(sql).toContain('returning a.*')
  })

  it('validates NFC restore references and duplicate UIDs while preserving older backups', () => {
    const restore = read('scripts/restore-backup.mjs')
    expect(restore).toContain("const nfcAssets = await readJson('oxxen_connect_nfc_assets.json', [])")
    expect(restore).toContain("throw new Error('Backup inválido: UID NFC duplicado.')")
    expect(restore).toContain("NFC vinculado a pedido ausente")
    expect(restore).toContain("NFC vinculado a order item ausente")
    expect(restore).toContain("NFC vinculado a tarjeta ausente")
    expect(restore).not.toContain('más de un NFC asociado a la misma tarjeta')
    expect(restore).toContain("await upsertBatches('oxxen_connect_nfc_assets', nfcAssets)")
  })
})
