-- OXXEN Connect — Sprint 3.1: formal customer entity + non-destructive card relationship
-- Safe for legacy cards: existing cards keep customer_id = NULL and public_id/slug/aliases are untouched.

create table if not exists public.oxxen_connect_customers (
  id uuid primary key default gen_random_uuid(),
  customer_number bigint generated by default as identity,
  customer_code text not null,
  business_name text,
  contact_name text,
  email text,
  phone text,
  whatsapp text,
  document_type text,
  document_number text,
  address text,
  notes text,
  status text not null default 'lead',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint oxxen_connect_customers_number_unique unique (customer_number),
  constraint oxxen_connect_customers_code_unique unique (customer_code),
  constraint oxxen_connect_customers_code_format check (customer_code ~ '^CLI-[0-9]{6,}$'),
  constraint oxxen_connect_customers_name_required check (
    nullif(btrim(coalesce(business_name, '')), '') is not null
    or nullif(btrim(coalesce(contact_name, '')), '') is not null
  ),
  constraint oxxen_connect_customers_status_check check (
    status in ('lead', 'active', 'inactive', 'blocked')
  ),
  constraint oxxen_connect_customers_document_type_check check (
    document_type is null or document_type in ('DNI', 'RUC', 'CE', 'PASSPORT', 'OTHER')
  )
);

create or replace function public.oxxen_connect_assign_customer_code()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.customer_code is null or btrim(new.customer_code) = '' then
    new.customer_code := 'CLI-' || lpad(new.customer_number::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_oxxen_connect_customers_assign_code
  on public.oxxen_connect_customers;
create trigger trg_oxxen_connect_customers_assign_code
before insert on public.oxxen_connect_customers
for each row execute function public.oxxen_connect_assign_customer_code();

create index if not exists idx_oxxen_connect_customers_status
  on public.oxxen_connect_customers(status);

create index if not exists idx_oxxen_connect_customers_created_at
  on public.oxxen_connect_customers(created_at desc);

alter table public.oxxen_connect_cards
  add column if not exists customer_id uuid;

-- Keep the relation nullable so legacy cards continue working without a customer row.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'oxxen_connect_cards_customer_id_fkey'
      and conrelid = 'public.oxxen_connect_cards'::regclass
  ) then
    alter table public.oxxen_connect_cards
      add constraint oxxen_connect_cards_customer_id_fkey
      foreign key (customer_id)
      references public.oxxen_connect_customers(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists idx_oxxen_connect_cards_customer_id
  on public.oxxen_connect_cards(customer_id)
  where customer_id is not null;

create or replace function public.oxxen_connect_touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_oxxen_connect_customers_touch_updated_at
  on public.oxxen_connect_customers;
create trigger trg_oxxen_connect_customers_touch_updated_at
before update on public.oxxen_connect_customers
for each row execute function public.oxxen_connect_touch_updated_at();

alter table public.oxxen_connect_customers enable row level security;

-- Explicit grants: public/anon cannot enumerate or mutate customers.
revoke all on table public.oxxen_connect_customers from public, anon;
grant select, insert, update on table public.oxxen_connect_customers to authenticated;
grant usage, select on sequence public.oxxen_connect_customers_customer_number_seq to authenticated;

-- Backup restore inserts explicit customer_number values. Resync the identity sequence afterwards.
create or replace function public.oxxen_connect_sync_customer_sequence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_max bigint;
begin
  select coalesce(max(c.customer_number), 0)
    into current_max
    from public.oxxen_connect_customers c;

  if current_max = 0 then
    perform setval('public.oxxen_connect_customers_customer_number_seq'::regclass, 1, false);
  else
    perform setval('public.oxxen_connect_customers_customer_number_seq'::regclass, current_max, true);
  end if;
end;
$$;

revoke all on function public.oxxen_connect_sync_customer_sequence() from public, anon, authenticated;
grant execute on function public.oxxen_connect_sync_customer_sequence() to service_role;

-- Every authenticated OXXEN admin role may read customer records.
drop policy if exists oxxen_customers_admin_read on public.oxxen_connect_customers;
create policy oxxen_customers_admin_read
on public.oxxen_connect_customers
for select
to authenticated
using (
  exists (
    select 1
    from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER', 'ADMIN', 'EDITOR', 'SUPPORT', 'SALES')
  )
);

-- Customer creation/update belongs to commercial/administrative roles.
drop policy if exists oxxen_customers_commercial_insert on public.oxxen_connect_customers;
create policy oxxen_customers_commercial_insert
on public.oxxen_connect_customers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER', 'ADMIN', 'SALES')
  )
);

drop policy if exists oxxen_customers_commercial_update on public.oxxen_connect_customers;
create policy oxxen_customers_commercial_update
on public.oxxen_connect_customers
for update
to authenticated
using (
  exists (
    select 1
    from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER', 'ADMIN', 'SALES')
  )
)
with check (
  exists (
    select 1
    from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER', 'ADMIN', 'SALES')
  )
);

-- No DELETE policy is created. Customer lifecycle uses status instead of hard-delete.

-- Keep the Sprint 2 OWNER MFA invariant for this new operational table.
drop policy if exists oxxen_customers_require_owner_aal2 on public.oxxen_connect_customers;
create policy oxxen_customers_require_owner_aal2
on public.oxxen_connect_customers
as restrictive
for all
to authenticated
using (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
)
with check (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
);

comment on table public.oxxen_connect_customers is
  'Commercial customer entity. One customer can own many digital cards; physical identity remains on cards.public_id.';

comment on column public.oxxen_connect_cards.customer_id is
  'Optional commercial owner relation. NULL is valid for legacy cards and never affects public_id/QR/NFC resolution.';
