-- OXXEN Connect — Sprint 3.3: NFC physical inventory lifecycle
-- Additive migration. It does not alter public_id, public profile resolution, aliases, QR/NFC legacy redirects or existing cards.

create table if not exists public.oxxen_connect_nfc_assets (
  id uuid primary key default gen_random_uuid(),
  asset_number bigint generated by default as identity,
  asset_code text not null,
  chip_type text not null,
  uid text,
  status text not null default 'available',
  order_id uuid references public.oxxen_connect_orders(id) on delete set null,
  order_item_id uuid references public.oxxen_connect_order_items(id) on delete set null,
  card_id uuid references public.oxxen_connect_cards(id) on delete set null,
  batch_code text,
  supplier text,
  purchase_cost numeric(12,2),
  notes text,
  programmed_at timestamptz,
  reserved_at timestamptz,
  delivered_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint oxxen_connect_nfc_assets_number_unique unique (asset_number),
  constraint oxxen_connect_nfc_assets_code_unique unique (asset_code),
  constraint oxxen_connect_nfc_assets_code_format check (asset_code ~ '^NFC-[0-9]{6,}$'),
  constraint oxxen_connect_nfc_assets_chip_type_check check (chip_type in ('NTAG213','NTAG215','NTAG216','NTAG424_DNA','OTHER')),
  constraint oxxen_connect_nfc_assets_status_check check (status in ('available','reserved','programmed','assigned','delivered','defective','lost','retired')),
  constraint oxxen_connect_nfc_assets_purchase_cost_check check (purchase_cost is null or purchase_cost >= 0),
  constraint oxxen_connect_nfc_assets_uid_format check (uid is null or uid ~ '^[0-9A-F]{8,32}$')
);

create unique index if not exists uq_oxxen_connect_nfc_assets_uid
  on public.oxxen_connect_nfc_assets(uid) where uid is not null;
create unique index if not exists uq_oxxen_connect_nfc_assets_card_id
  on public.oxxen_connect_nfc_assets(card_id) where card_id is not null;
create index if not exists idx_oxxen_connect_nfc_assets_status on public.oxxen_connect_nfc_assets(status);
create index if not exists idx_oxxen_connect_nfc_assets_chip_type on public.oxxen_connect_nfc_assets(chip_type);
create index if not exists idx_oxxen_connect_nfc_assets_order_id on public.oxxen_connect_nfc_assets(order_id) where order_id is not null;
create index if not exists idx_oxxen_connect_nfc_assets_order_item_id on public.oxxen_connect_nfc_assets(order_item_id) where order_item_id is not null;
create index if not exists idx_oxxen_connect_nfc_assets_batch_code on public.oxxen_connect_nfc_assets(batch_code) where batch_code is not null;
create index if not exists idx_oxxen_connect_nfc_assets_created_at on public.oxxen_connect_nfc_assets(created_at desc);

create or replace function public.oxxen_connect_prepare_nfc_asset()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_item_order uuid;
begin
  new.asset_code := 'NFC-' || lpad(new.asset_number::text, 6, '0');
  new.uid := nullif(upper(regexp_replace(coalesce(new.uid, ''), '[^0-9a-fA-F]', '', 'g')), '');
  new.batch_code := nullif(upper(trim(coalesce(new.batch_code, ''))), '');
  new.supplier := nullif(trim(coalesce(new.supplier, '')), '');
  new.notes := nullif(trim(coalesce(new.notes, '')), '');

  if new.order_item_id is not null then
    select i.order_id into v_item_order
    from public.oxxen_connect_order_items i
    where i.id = new.order_item_id;
    if v_item_order is null then
      raise exception 'order_item_id no existe' using errcode = '23503';
    end if;
    if new.order_id is null then
      new.order_id := v_item_order;
    elsif new.order_id <> v_item_order then
      raise exception 'order_item_id no pertenece al order_id seleccionado' using errcode = '23514';
    end if;
  end if;

  if new.status = 'reserved' and new.order_id is null then
    raise exception 'Un NFC reservado debe estar asociado a un pedido' using errcode = '23514';
  end if;
  if new.status in ('programmed','assigned','delivered') and new.uid is null then
    raise exception 'Un NFC programado/asignado/entregado requiere UID' using errcode = '23514';
  end if;
  if new.status in ('assigned','delivered') and new.card_id is null then
    raise exception 'Un NFC asignado/entregado requiere card_id' using errcode = '23514';
  end if;

  if tg_op = 'INSERT' then
    if auth.uid() is not null then new.created_by := auth.uid(); end if;
  elsif old.status is distinct from new.status then
    if not (
      (old.status = 'available' and new.status in ('reserved','defective','lost','retired')) or
      (old.status = 'reserved' and new.status in ('available','programmed','defective','lost','retired')) or
      (old.status = 'programmed' and new.status in ('assigned','defective','lost','retired')) or
      (old.status = 'assigned' and new.status in ('delivered','defective','lost','retired')) or
      (old.status = 'defective' and new.status = 'retired') or
      (old.status = 'lost' and new.status = 'retired')
    ) then
      raise exception 'Transición NFC inválida: % -> %', old.status, new.status using errcode = '23514';
    end if;
  end if;

  if new.status = 'reserved' then new.reserved_at := coalesce(new.reserved_at, now()); end if;
  if new.status = 'available' then new.reserved_at := null; end if;
  if new.status = 'programmed' then new.programmed_at := coalesce(new.programmed_at, now()); end if;
  if new.status = 'delivered' then new.delivered_at := coalesce(new.delivered_at, now()); end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_oxxen_connect_prepare_nfc_asset on public.oxxen_connect_nfc_assets;
create trigger trg_oxxen_connect_prepare_nfc_asset
before insert or update on public.oxxen_connect_nfc_assets
for each row execute function public.oxxen_connect_prepare_nfc_asset();

create or replace function public.oxxen_connect_sync_nfc_asset_sequence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_max bigint;
begin
  select coalesce(max(a.asset_number), 0) into current_max from public.oxxen_connect_nfc_assets a;
  if current_max = 0 then
    perform setval('public.oxxen_connect_nfc_assets_asset_number_seq'::regclass, 1, false);
  else
    perform setval('public.oxxen_connect_nfc_assets_asset_number_seq'::regclass, current_max, true);
  end if;
end;
$$;
revoke all on function public.oxxen_connect_sync_nfc_asset_sequence() from public, anon, authenticated;
grant execute on function public.oxxen_connect_sync_nfc_asset_sequence() to service_role;

alter table public.oxxen_connect_nfc_assets enable row level security;
revoke all on table public.oxxen_connect_nfc_assets from public, anon, authenticated;
revoke all on sequence public.oxxen_connect_nfc_assets_asset_number_seq from public, anon, authenticated;

grant select on table public.oxxen_connect_nfc_assets to authenticated;
grant insert (chip_type,uid,status,order_id,order_item_id,card_id,batch_code,supplier,purchase_cost,notes)
  on table public.oxxen_connect_nfc_assets to authenticated;
grant update (uid,status,order_id,order_item_id,card_id,batch_code,supplier,purchase_cost,notes)
  on table public.oxxen_connect_nfc_assets to authenticated;
grant usage, select on sequence public.oxxen_connect_nfc_assets_asset_number_seq to authenticated;

create policy oxxen_nfc_assets_admin_read
on public.oxxen_connect_nfc_assets for select to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','EDITOR','SUPPORT','SALES')
  )
);

create policy oxxen_nfc_assets_admin_insert
on public.oxxen_connect_nfc_assets for insert to authenticated
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN')
  )
);

create policy oxxen_nfc_assets_admin_update
on public.oxxen_connect_nfc_assets for update to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN')
  )
)
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN')
  )
);

create policy oxxen_nfc_assets_require_owner_aal2
on public.oxxen_connect_nfc_assets as restrictive for all to authenticated
using (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
)
with check (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
);

create or replace function public.oxxen_connect_bulk_create_nfc_assets(
  p_chip_type text,
  p_quantity integer,
  p_batch_code text default null,
  p_supplier text default null,
  p_purchase_cost numeric default null,
  p_notes text default null
)
returns setof public.oxxen_connect_nfc_assets
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text;
  v_row public.oxxen_connect_nfc_assets%rowtype;
  i integer;
begin
  select a.role into v_role
  from public.oxxen_connect_admins a
  where a.user_id = auth.uid();

  if v_role not in ('OWNER','ADMIN') then
    raise exception 'Permiso insuficiente para crear inventario NFC' using errcode = '42501';
  end if;
  if v_role = 'OWNER' and coalesce(auth.jwt()->>'aal','aal1') <> 'aal2' then
    raise exception 'OWNER requiere AAL2' using errcode = '42501';
  end if;
  if p_quantity is null or p_quantity < 1 or p_quantity > 500 then
    raise exception 'La cantidad debe estar entre 1 y 500' using errcode = '22023';
  end if;

  for i in 1..p_quantity loop
    insert into public.oxxen_connect_nfc_assets(chip_type,batch_code,supplier,purchase_cost,notes,created_by)
    values (p_chip_type,p_batch_code,p_supplier,p_purchase_cost,p_notes,auth.uid())
    returning * into v_row;
    return next v_row;
  end loop;

  insert into public.oxxen_connect_audit_logs(admin_id, action, entity_type, old_value, new_value, metadata)
  values (
    auth.uid(), 'nfc.bulk_created', 'nfc_asset', null, null,
    jsonb_build_object('quantity', p_quantity, 'chip_type', p_chip_type, 'batch_code', p_batch_code)
  );
  return;
end;
$$;
revoke all on function public.oxxen_connect_bulk_create_nfc_assets(text,integer,text,text,numeric,text) from public, anon;
grant execute on function public.oxxen_connect_bulk_create_nfc_assets(text,integer,text,text,numeric,text) to authenticated;

create or replace function public.oxxen_connect_audit_nfc_asset_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text := 'nfc.updated';
begin
  if tg_op = 'INSERT' then
    v_action := 'nfc.created';
  elsif old.status is distinct from new.status then
    v_action := case new.status
      when 'reserved' then 'nfc.reserved'
      when 'available' then 'nfc.released'
      when 'programmed' then 'nfc.programmed'
      when 'assigned' then 'nfc.card_assigned'
      when 'delivered' then 'nfc.delivered'
      when 'defective' then 'nfc.defective'
      when 'lost' then 'nfc.lost'
      when 'retired' then 'nfc.retired'
      else 'nfc.updated' end;
  elsif old.uid is distinct from new.uid then
    v_action := 'nfc.uid_registered';
  elsif old.card_id is distinct from new.card_id then
    v_action := 'nfc.card_assigned';
  end if;

  insert into public.oxxen_connect_audit_logs(admin_id, card_id, action, entity_type, entity_id, old_value, new_value, metadata)
  values (
    auth.uid(), new.card_id, v_action, 'nfc_asset', new.id,
    case when tg_op = 'INSERT' then null else jsonb_build_object('status',old.status,'uid',old.uid,'order_id',old.order_id,'card_id',old.card_id) end,
    jsonb_build_object('status',new.status,'uid',new.uid,'order_id',new.order_id,'card_id',new.card_id),
    jsonb_build_object('asset_code',new.asset_code,'chip_type',new.chip_type,'batch_code',new.batch_code)
  );
  return new;
end;
$$;
revoke all on function public.oxxen_connect_audit_nfc_asset_change() from public, anon, authenticated;

drop trigger if exists trg_oxxen_connect_audit_nfc_asset_change on public.oxxen_connect_nfc_assets;
create trigger trg_oxxen_connect_audit_nfc_asset_change
after insert or update on public.oxxen_connect_nfc_assets
for each row execute function public.oxxen_connect_audit_nfc_asset_change();

comment on table public.oxxen_connect_nfc_assets is 'Physical NFC inventory. public_id remains the permanent digital identity on oxxen_connect_cards.';
comment on column public.oxxen_connect_nfc_assets.uid is 'Normalized physical chip UID; never used as public card identity.';
