-- OXXEN Connect — Sprint 3.2: orders + order lifecycle
-- This migration is intentionally additive. It does not modify card public_id, slug, aliases, QR/NFC resolution, MFA or public RPCs.

create table if not exists public.oxxen_connect_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity,
  order_code text not null,
  customer_id uuid not null references public.oxxen_connect_customers(id) on delete restrict,
  status text not null default 'draft',
  payment_status text not null default 'pending',
  currency text not null default 'PEN',
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  quantity integer not null default 1,
  notes text,
  created_by uuid,
  confirmed_at timestamptz,
  production_started_at timestamptz,
  ready_at timestamptz,
  delivered_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint oxxen_connect_orders_number_unique unique (order_number),
  constraint oxxen_connect_orders_code_unique unique (order_code),
  constraint oxxen_connect_orders_code_format check (order_code ~ '^ORD-[0-9]{6,}$'),
  constraint oxxen_connect_orders_status_check check (status in ('draft','confirmed','in_production','ready','delivered','cancelled')),
  constraint oxxen_connect_orders_payment_status_check check (payment_status in ('pending','partial','paid','refunded')),
  constraint oxxen_connect_orders_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint oxxen_connect_orders_subtotal_check check (subtotal >= 0),
  constraint oxxen_connect_orders_discount_check check (discount >= 0),
  constraint oxxen_connect_orders_total_check check (total >= 0),
  constraint oxxen_connect_orders_quantity_check check (quantity >= 0)
);

create table if not exists public.oxxen_connect_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.oxxen_connect_orders(id) on delete cascade,
  item_type text not null,
  description text,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  subtotal numeric(12,2) not null default 0,
  card_id uuid references public.oxxen_connect_cards(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint oxxen_connect_order_items_type_check check (item_type in ('digital_card','nfc_card','service','other')),
  constraint oxxen_connect_order_items_quantity_check check (quantity > 0),
  constraint oxxen_connect_order_items_unit_price_check check (unit_price >= 0),
  constraint oxxen_connect_order_items_subtotal_check check (subtotal >= 0)
);

create index if not exists idx_oxxen_connect_orders_customer_id on public.oxxen_connect_orders(customer_id);
create index if not exists idx_oxxen_connect_orders_status on public.oxxen_connect_orders(status);
create index if not exists idx_oxxen_connect_orders_payment_status on public.oxxen_connect_orders(payment_status);
create index if not exists idx_oxxen_connect_orders_created_at on public.oxxen_connect_orders(created_at desc);
create index if not exists idx_oxxen_connect_order_items_order_id on public.oxxen_connect_order_items(order_id);
create index if not exists idx_oxxen_connect_order_items_card_id on public.oxxen_connect_order_items(card_id) where card_id is not null;

create or replace function public.oxxen_connect_prepare_order()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.order_code := 'ORD-' || lpad(new.order_number::text, 6, '0');
    new.subtotal := 0;
    new.quantity := 0;
    new.total := 0;
    if auth.uid() is not null then new.created_by := auth.uid(); end if;
  else
    new.total := greatest(new.subtotal - new.discount, 0);
  end if;

  if tg_op = 'UPDATE' and old.status is distinct from new.status then
    if not (
      (old.status = 'draft' and new.status in ('confirmed','cancelled')) or
      (old.status = 'confirmed' and new.status in ('in_production','cancelled')) or
      (old.status = 'in_production' and new.status in ('ready','cancelled')) or
      (old.status = 'ready' and new.status in ('delivered','cancelled'))
    ) then
      raise exception 'Transición de pedido inválida: % -> %', old.status, new.status using errcode = '23514';
    end if;

    if new.status = 'confirmed' then new.confirmed_at := coalesce(new.confirmed_at, now()); end if;
    if new.status = 'in_production' then new.production_started_at := coalesce(new.production_started_at, now()); end if;
    if new.status = 'ready' then new.ready_at := coalesce(new.ready_at, now()); end if;
    if new.status = 'delivered' then new.delivered_at := coalesce(new.delivered_at, now()); end if;
    if new.status = 'cancelled' then new.cancelled_at := coalesce(new.cancelled_at, now()); end if;
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_oxxen_connect_prepare_order on public.oxxen_connect_orders;
create trigger trg_oxxen_connect_prepare_order
before insert or update on public.oxxen_connect_orders
for each row execute function public.oxxen_connect_prepare_order();

create or replace function public.oxxen_connect_prepare_order_item()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.subtotal := round((new.quantity * new.unit_price)::numeric, 2);
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_oxxen_connect_prepare_order_item on public.oxxen_connect_order_items;
create trigger trg_oxxen_connect_prepare_order_item
before insert or update on public.oxxen_connect_order_items
for each row execute function public.oxxen_connect_prepare_order_item();

create or replace function public.oxxen_connect_recalculate_order_totals()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid := coalesce(new.order_id, old.order_id);
  v_subtotal numeric(12,2);
  v_quantity integer;
begin
  select coalesce(sum(i.subtotal), 0), coalesce(sum(i.quantity), 0)
    into v_subtotal, v_quantity
    from public.oxxen_connect_order_items i
    where i.order_id = v_order_id;

  update public.oxxen_connect_orders o
     set subtotal = v_subtotal,
         quantity = v_quantity,
         total = greatest(v_subtotal - o.discount, 0),
         updated_at = now()
   where o.id = v_order_id;

  return coalesce(new, old);
end;
$$;

revoke all on function public.oxxen_connect_recalculate_order_totals() from public, anon, authenticated;

drop trigger if exists trg_oxxen_connect_recalculate_order_totals on public.oxxen_connect_order_items;
create trigger trg_oxxen_connect_recalculate_order_totals
after insert or update or delete on public.oxxen_connect_order_items
for each row execute function public.oxxen_connect_recalculate_order_totals();

create or replace function public.oxxen_connect_sync_order_sequence()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_max bigint;
begin
  select coalesce(max(o.order_number), 0) into current_max from public.oxxen_connect_orders o;
  if current_max = 0 then
    perform setval('public.oxxen_connect_orders_order_number_seq'::regclass, 1, false);
  else
    perform setval('public.oxxen_connect_orders_order_number_seq'::regclass, current_max, true);
  end if;
end;
$$;
revoke all on function public.oxxen_connect_sync_order_sequence() from public, anon, authenticated;
grant execute on function public.oxxen_connect_sync_order_sequence() to service_role;

alter table public.oxxen_connect_orders enable row level security;
alter table public.oxxen_connect_order_items enable row level security;

revoke all on table public.oxxen_connect_orders from public, anon, authenticated;
revoke all on table public.oxxen_connect_order_items from public, anon, authenticated;
revoke all on sequence public.oxxen_connect_orders_order_number_seq from public, anon, authenticated;

grant select on table public.oxxen_connect_orders to authenticated;
grant insert (customer_id,status,payment_status,currency,discount,notes) on table public.oxxen_connect_orders to authenticated;
grant update (customer_id,status,payment_status,currency,discount,notes) on table public.oxxen_connect_orders to authenticated;
grant usage, select on sequence public.oxxen_connect_orders_order_number_seq to authenticated;

grant select on table public.oxxen_connect_order_items to authenticated;
grant insert (order_id,item_type,description,quantity,unit_price,card_id) on table public.oxxen_connect_order_items to authenticated;
grant update (item_type,description,quantity,unit_price,card_id) on table public.oxxen_connect_order_items to authenticated;

create policy oxxen_orders_admin_read
on public.oxxen_connect_orders for select to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','EDITOR','SUPPORT','SALES')
  )
);

create policy oxxen_orders_commercial_insert
on public.oxxen_connect_orders for insert to authenticated
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
);

create policy oxxen_orders_commercial_update
on public.oxxen_connect_orders for update to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
)
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
);

create policy oxxen_order_items_admin_read
on public.oxxen_connect_order_items for select to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','EDITOR','SUPPORT','SALES')
  )
);

create policy oxxen_order_items_commercial_insert
on public.oxxen_connect_order_items for insert to authenticated
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
);

create policy oxxen_order_items_commercial_update
on public.oxxen_connect_order_items for update to authenticated
using (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
)
with check (
  exists (
    select 1 from public.oxxen_connect_admins a
    where a.user_id = (select auth.uid())
      and a.role in ('OWNER','ADMIN','SALES')
  )
);

create policy oxxen_orders_require_owner_aal2
on public.oxxen_connect_orders as restrictive for all to authenticated
using (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
)
with check (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
);

create policy oxxen_order_items_require_owner_aal2
on public.oxxen_connect_order_items as restrictive for all to authenticated
using (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
)
with check (
  not public.oxxen_connect_current_admin_requires_aal2()
  or (select auth.jwt()->>'aal') = 'aal2'
);

-- Generic entity id keeps order auditing queryable without weakening the existing card audit schema.
alter table public.oxxen_connect_audit_logs add column if not exists entity_id uuid;
create index if not exists idx_oxxen_connect_audit_entity_created
  on public.oxxen_connect_audit_logs(entity_type, entity_id, created_at desc);

create or replace function public.oxxen_connect_audit_order_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text;
begin
  if tg_op = 'INSERT' then
    insert into public.oxxen_connect_audit_logs(admin_id, action, entity_type, entity_id, old_value, new_value, metadata)
    values (auth.uid(), 'order.created', 'order', new.id, null, to_jsonb(new), jsonb_build_object('order_code', new.order_code));
    return new;
  end if;

  if old.status is distinct from new.status then
    v_action := case new.status
      when 'confirmed' then 'order.confirmed'
      when 'in_production' then 'order.production_started'
      when 'ready' then 'order.ready'
      when 'delivered' then 'order.delivered'
      when 'cancelled' then 'order.cancelled'
      else 'order.updated' end;
  elsif old.payment_status is distinct from new.payment_status then
    v_action := 'order.payment_status_changed';
  elsif old.customer_id is distinct from new.customer_id
     or old.discount is distinct from new.discount
     or old.notes is distinct from new.notes then
    v_action := 'order.updated';
  else
    return new;
  end if;

  insert into public.oxxen_connect_audit_logs(admin_id, action, entity_type, entity_id, old_value, new_value, metadata)
  values (auth.uid(), v_action, 'order', new.id, to_jsonb(old), to_jsonb(new), jsonb_build_object('order_code', new.order_code));
  return new;
end;
$$;
revoke all on function public.oxxen_connect_audit_order_change() from public, anon, authenticated;

drop trigger if exists trg_oxxen_connect_audit_order_change on public.oxxen_connect_orders;
create trigger trg_oxxen_connect_audit_order_change
after insert or update on public.oxxen_connect_orders
for each row execute function public.oxxen_connect_audit_order_change();

create or replace function public.oxxen_connect_audit_order_item_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_action text := 'order_item.updated';
begin
  if tg_op = 'INSERT' then v_action := 'order_item.created';
  elsif old.card_id is distinct from new.card_id then v_action := 'order_item.card_assigned';
  end if;

  insert into public.oxxen_connect_audit_logs(admin_id, card_id, action, entity_type, entity_id, old_value, new_value, metadata)
  values (
    auth.uid(),
    new.card_id,
    v_action,
    'order_item',
    new.id,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new),
    jsonb_build_object('order_id', new.order_id)
  );
  return new;
end;
$$;
revoke all on function public.oxxen_connect_audit_order_item_change() from public, anon, authenticated;

drop trigger if exists trg_oxxen_connect_audit_order_item_change on public.oxxen_connect_order_items;
create trigger trg_oxxen_connect_audit_order_item_change
after insert or update on public.oxxen_connect_order_items
for each row execute function public.oxxen_connect_audit_order_item_change();

comment on table public.oxxen_connect_orders is 'Commercial orders. Operational only; never used as public card identity.';
comment on table public.oxxen_connect_order_items is 'Order line items. card_id is optional until a digital card is assigned.';
